# Generated by Django 5.0 on 2023-12-12 04:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('updated_at', models.TimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('contact_details', models.TextField(verbose_name='Contact Details')),
                ('address', models.TextField(verbose_name='Address')),
                ('vendor_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('on_time_delivery_rate', models.FloatField(blank=True, null=True, verbose_name='On Time Delivery Rate')),
                ('quality_rating_avg', models.FloatField(blank=True, null=True, verbose_name='Quality Rating Average')),
                ('average_response_time', models.FloatField(blank=True, null=True, verbose_name='Average Rating Response')),
                ('fulfillment_rate', models.FloatField(blank=True, null=True, verbose_name='Fulfillement Rate')),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('updated_at', models.TimeField(auto_now=True)),
                ('po_number', models.CharField(max_length=50, unique=True)),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Order Date')),
                ('delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='Delivery Date')),
                ('items', models.JSONField(verbose_name='Items Ordered')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=15, verbose_name='Order Status')),
                ('quality_rating', models.FloatField(blank=True, null=True, verbose_name='Quality Rating')),
                ('issue_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Issued')),
                ('acknowledge_date', models.DateTimeField(blank=True, null=True, verbose_name='Acknowledgement Date')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actualtask.vendor')),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPerfomance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.TimeField(auto_now_add=True)),
                ('updated_at', models.TimeField(auto_now=True)),
                ('date', models.DateTimeField()),
                ('on_time_delivery_rate', models.FloatField(blank=True, null=True, verbose_name='On Time Delivery Rate')),
                ('quality_rating_avg', models.FloatField(blank=True, null=True, verbose_name='Quality Rating Average')),
                ('average_response_time', models.FloatField(verbose_name='Average Rating Response')),
                ('fulfillment_rate', models.FloatField(verbose_name='Fulfillement Rate')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actualtask.vendor')),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
            },
        ),
    ]
