# Generated by Django 5.0 on 2023-12-12 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actualtask', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HistoricalPerfomance',
            new_name='HistoricalPerformance',
        ),
        migrations.AlterModelOptions(
            name='historicalperformance',
            options={'verbose_name': 'Historical Performance', 'verbose_name_plural': 'Historical Performances'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'verbose_name': 'Purchase Order', 'verbose_name_plural': 'Purchase Orders'},
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_code',
        ),
    ]
